server:
    port: 443
    ssl:
        enabled: true
        key-store-type: PKCS12
        key-store: classpath:keystore/baeldung.p12
        key-store-password: 070903
        key-alias: baeldung
spring:
    application.name: rythm
    servlet.multipart:
        max-file-size: 100MB
        max-request-size: 100MB

    datasource:
        url: jdbc:h2:file:./local-database/data
        username: user
        password:

    jpa:
        defer-datasource-initialization: true
        show-sql: true
        hibernate.ddl-auto: update
    h2.console.enabled: true
