spring:
    application.name: rythm
    servlet.multipart:
            max-file-size: 100MB
            max-request-size: 100MB

    datasource:
        url: jdbc:postgresql://localhost:5432/rythm
        username: postgres
        password: postgres
    jpa: 
        hibernate.ddl-auto: create-drop
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        