server:
    port: 443
    ssl:
        certificate: classpath:certificates/lets-encrypt/fullchain.pem
        certificate-private-key: classpath:certificates/lets-encrypt/privkey.pem
        enabled: true
spring:
    application.name: rythm

    security.oauth2.client.registration:
        google:
            client-id: 584372132949-stsv429904cqpdfkhg2842mpnd5h3hmm.apps.googleusercontent.com
            client-secret: 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

    servlet.multipart:
        max-file-size: 100MB
        max-request-size: 100MB

    datasource:
        url: jdbc:h2:file:./local-database/data
        username: user
        password:

    jpa:
        defer-datasource-initialization: true
        show-sql: true
        hibernate.ddl-auto: update
    h2.console.enabled: true
