server:
    port: 443
    ssl:
        certificate: classpath:certificates/lets-encrypt/fullchain.pem
        certificate-private-key: classpath:certificates/lets-encrypt/privkey.pem
        enabled: true
logging.level:
    web: debug
spring:
    application.name: rythm

    security.oauth2.client:
        provider:
            osu:
                authorization-uri: https://osu.ppy.sh/oauth/authorize
                token-uri: https://osu.ppy.sh/oauth/token
                user-info-uri: https://osu.ppy.sh/api/v2/me
                user-name-attribute: username
            google:
                user-name-attribute: email
        registration:
            osu:
                authorization-grant-type: authorization_code
                redirect-uri: https://localhost/login/oauth2/code/osu
                client-authentication-method: client_secret_basic
                client-id: 37570
                client-secret: PeDaJbeTK7fyKJDB53PJh6RyiLjXNCbj6XmnycNJ
            google:
                client-id: 584372132949-stsv429904cqpdfkhg2842mpnd5h3hmm.apps.googleusercontent.com
                client-secret: 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

    servlet.multipart:
        max-file-size: 100MB
        max-request-size: 100MB

    datasource:
        url: jdbc:h2:file:./local-database/data
        username: user
        password:

    jpa:
        defer-datasource-initialization: true
        show-sql: true
        hibernate.ddl-auto: update
    h2.console.enabled: true
