name: run-website
on: 
    workflow_dispatch:

jobs:
    run-website:
        runs-on: self-hosted
        timeout-minutes: 43800
        steps:
            - uses: actions/checkout@v2
            - run: ./run.bat